<?php
/**
 * Configuration file for 'yii message/extract' command.
 *
 * This file is automatically generated by 'yii message/config' command.
 * It contains parameters for source code messages extraction.
 * You may modify this file to suit your needs.
 *
 * You can use 'yii message/config-template' command to create
 * template configuration file with detailed description for each parameter.
 */
return [
    'color' => true,
    'interactive' => true,
    'sourcePath' => '@app',
    'messagePath' => 'messages',
    'languages' => [
        'en-US'
    ],
    'translator' => 'Yii::t',
    'except' => [
        '.svn',
        '.git',
        '.gitignore',
        '.gitkeep',
        '.hgignore',
        '.hgkeep',
        '/messages',
        '/BaseYii.php',
        '/vendor',
    ],
    'only' => [
        '*.php'
    ],
    'ignoreCategories' => [
        'yii',
    ],
    // 是否应该用合并的消息覆盖消息文件
    'overwrite' => true,
    // 是否删除源代码中不再出现的消息。
    'removeUnused' => false,
    // 是否标记源代码中不再出现的消息。
    'markUnused' => true,
];
